name: Test application

on:
  pull_request:
    branches: [ master, qa ]

jobs:
  needTest:
    runs-on: ubuntu-latest
    outputs:
        canSkip: ${{ steps.checkFiles.outputs.canSkip }}
    steps:
    - name: Check files in PR
      id: checkFiles
      run: |
           PR_FILES_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{github.event.pull_request.number}}/files"
           FILES_CHANGED=$(curl -s -X GET -G $PR_FILES_URL | jq -r '.[] | .filename')
           echo $FILES_CHANGED
           if [ ${#FILES_CHANGED[@]} == 1 ] && [ ${FILES_CHANGED[0]} == README.adoc ]; then
             echo "Test can be skipped because only updated README.adoc"
             echo "::set-output name=canSkip::true"
           else
             echo "Need to run test"           
             echo "::set-output name=canSkip::false"
           fi
  java8build:
    runs-on: ubuntu-latest
    needs: [needTest]
    if: "!contains(needs.needTest.outputs.canSkip, 'true')"
    env:
      CHANGE_MINIKUBE_NONE_USER: true
    defaults:
      run:
        working-directory: finish

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: unset _JAVA_OPTIONS
    - name: Set up Minikube
      run: |
        /usr/local/bin/kubectl version
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        ./kubectl version
        sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
        wget https://github.com/kubernetes/minikube/releases/download/v0.28.2/minikube-linux-amd64 -q -O minikube
        chmod +x minikube
        CHANGE_MINIKUBE_NONE_USER=true
    - name: Install Conn Track
      run: |
        sudo apt-get update -y
        sudo apt-get install -y conntrack
    - name: Start Minikube
      run: sudo minikube start --vm-driver=none --bootstrapper=kubeadm
    - name: Run tests
      run: chmod +x ../scripts/travisTest.sh && sudo ../scripts/travisTest.sh
    - name: Post tests
      if: always()
      run: sudo docker images
